/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("change");
    	System.out.println("2nd change");
        return true;
    }
}
